services:
  dejavu-similarity-api:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "${APP_PORT}:${APP_PORT}"
        
    environment:
      APP_PORT: ${APP_PORT}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_EXPIRED_TOKEN: ${AUTH_EXPIRED_TOKEN}
      AUTH_REFRESH_TOKEN: ${AUTH_REFRESH_TOKEN}
      POSTGRES_URL: ${POSTGRES_URL}
      TRANSCRIPTION_API_URL: ${TRANSCRIPTION_API_URL}
      TRANSCRIPTION_API_TOKEN: ${TRANSCRIPTION_API_TOKEN}
      TRANSCRIPTION_MODEL: ${TRANSCRIPTION_MODEL}
      RUST_BACKTRACE: ${RUST_BACKTRACE}
      FILE_SUBMIT_INTERVAL: ${FILE_SUBMIT_INTERVAL}
      SEMANTIC_DETECTOR_PATH: ${SEMANTIC_DETECTOR_PATH}
      SIMILARITY_THRESHOLD: ${SIMILARITY_THRESHOLD}
      AUTO_APPROVAL_THRESHOLD: ${AUTO_APPROVAL_THRESHOLD}
      PARTIAL_MATCH_THRESHOLD: ${PARTIAL_MATCH_THRESHOLD}
      
    restart: unless-stopped